### ISSUE TITLE
cuda outof memory with 5min audio input 

### ISSUE THREAD

**Issue by Zha-JiChi** [psyai-net/EmoTalk_release#24]
gpu: A100-80G

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.17 GiB (GPU 0; 79.19 GiB total capacity; 62.80 GiB already allocated; 1.50 GiB free; 64.06 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by jinqiupeter** [comment]
It's not optimized obviously. I had a 4:30min long audio and it took ~115G memory to generate the blendshape, I had to use CPU and increase swap memory:

**Comment by jinqiupeter** [comment]
<img width="1044" alt="WechatIMG556" src="https://github.com/psyai-net/EmoTalk_release/assets/12045814/1510e3b5-4d36-4d61-b505-fc60c649c6d0">

**Comment by hungho77** [comment]
Can I ask why when running with aud.wav from May.mp4, my output shape is different from the shape of the bs.npy file in the author's download. I am (7062, 52) compared to the author's (6073, 52).

**Comment by xiaoniuchushi** [comment]
> 请问为什么当使用 May.mp4 中的 aud.wav 运行时，我的输出形状与作者下载中的 bs.npy 文件的形状不同。与作者的 (6073, 52) 相比，我是 (7062, 52)。

Perhaps due to the default fps of 30 in the code

**Comment by hungho77** [comment]
> > 请问为什么当使用 May.mp4 中的 aud.wav 运行时，我的输出形状与作者下载中的 bs.npy 文件的形状不同。与作者的 (6073, 52) 相比，我是 (7062, 52)。
> 
> Perhaps due to the default fps of 30 in the code

![image](https://github.com/psyai-net/EmoTalk_release/assets/33565770/f51d58e0-5eee-4f91-b174-fc51f177960e)
![image](https://github.com/psyai-net/EmoTalk_release/assets/33565770/b0f5f08f-804b-4d14-b98f-97d7023dddac)
![image](https://github.com/psyai-net/EmoTalk_release/assets/33565770/cfb7ff44-ae24-482b-a6ff-eefcd8bb4e06)

thank for your advice, i have changed three lines in code and it worked. I don't know if it is riight but the shape output is correct (6073, 52)

**Comment by Tiandishihua** [comment]
> Can I ask why when running with aud.wav from May.mp4, my output shape is different from the shape of the bs.npy file in the author's download. I am (7062, 52) compared to the author's (6073, 52).

请问你的GPU没有爆显存吗？我的A100都扛不住

**Comment by 2hiTee** [comment]
> > > 请问为什么当使用 May.mp4 中的 aud.wav 运行时，我的输出形状与作者下载中的 bs.npy 文件的形状不同。与作者的 (6073, 52) 相比，我是 (7062, 52)。
> > 
> > 
> > Perhaps due to the default fps of 30 in the code
> 
> ![image](https://private-user-images.githubusercontent.com/33565770/320346891-f51d58e0-5eee-4f91-b174-fc51f177960e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5ODQ3MDYsIm5iZiI6MTcxODk4NDQwNiwicGF0aCI6Ii8zMzU2NTc3MC8zMjAzNDY4OTEtZjUxZDU4ZTAtNWVlZS00ZjkxLWIxNzQtZmM1MWYxNzc5NjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDE1NDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZDgzYzRhNWU5ZTFjYTgwODBlYTQ1YTJmYWFhNGY5MTIwMTg1ZmVmZjhkNGViYjMzY2I2YzJkMzYwODM1ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zb9URnDkS0qUPccs49yziOM8sy-IGu4jb-A7ZViOYfY) ![image](https://private-user-images.githubusercontent.com/33565770/320347016-b0f5f08f-804b-4d14-b98f-97d7023dddac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5ODQ3MDYsIm5iZiI6MTcxODk4NDQwNiwicGF0aCI6Ii8zMzU2NTc3MC8zMjAzNDcwMTYtYjBmNWYwOGYtODA0Yi00ZDE0LWI5OGYtOTdkNzAyM2RkZGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDE1NDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkZWU5NWI0MjdmYzU4NmVlNTI1MjMwOGE4ZmVhODhkZmE5ZjQwMmQ2ODRlYjk0NjQ2Yjk3NWM1ODE3ZWZiMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7em05wuRX-rcO0EQI9LaPkbzA_3mXG_K82N406tWnuo) ![image](https://private-user-images.githubusercontent.com/33565770/320347063-cfb7ff44-ae24-482b-a6ff-eefcd8bb4e06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5ODQ3MDYsIm5iZiI6MTcxODk4NDQwNiwicGF0aCI6Ii8zMzU2NTc3MC8zMjAzNDcwNjMtY2ZiN2ZmNDQtYWUyNC00ODJiLWE2ZmYtZWVmY2Q4YmI0ZTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDE1NDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMWYzYjMyNjU5MWYwYjA5Y2I0NThjZGVjZDUzZGZmMGIzMWVmYzE3MTQ5YjE1Yzg3ZDgxNWYxMTIzNjRmNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rjWrNpWLDQ9-bvDhrN17r39fuijd-jJteGrNAjzs8EQ)
> 
> thank for your advice, i have changed three lines in code and it worked. I don't know if it is riight but the shape output is correct (6073, 52)

Have you tried it? I change the code as you did, but the output video is all black. Thank you for your help!
